sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ricky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ricky/react-test npm test

after_success:
  - docker build -t rickyhsieh0302/multi-client ./client
  - docker build -t rickyhsieh0302/multi-nginx ./nginx
  - docker build -t rickyhsieh0302/multi-server ./server
  - docker build -t rickyhsieh0302/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rickyhsieh0302/multi-client
  - docker push rickyhsieh0302/multi-nginx
  - docker push rickyhsieh0302/multi-server
  - docker push rickyhsieh0302/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'multi-docker'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-897523482061'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY