sudo: required
services:
  -docker

before_install:
  - docker build -t ricky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ricky/react-test npm test

after_success:
  - docker build -t ricky/multi-client -f ./client
  - docker build -t ricky/multi-nginx ./nginx
  - docker build -t ricky/multi-server ./server
  - docker build -t ricky/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push ricky/multi-client
  - docker push ricky/multi-nginx
  - docker push ricky/multi-server
  - docker push ricky/multi-worker


language: generic